development:
  bucket: bucket-dev
  access_key_id: "AKIAJTP2DY2OUFVKPLKA"
  secret_access_key: "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"
test:
  bucket: bucket-test
  access_key_id: "AKIAJTP2DY2OUFVKPLKA"
  secret_access_key: "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"
production:
  bucket: bucket-pro
  access_key_id: "AKIAJTP2DY2OUFVKPLKA"
  secret_access_key: "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"